attribution: false

social:

  - title: "Facebook Jacobina Arte France"
    icon: "fa-facebook-f"
    url: "https://www.facebook.com/groups/jacobinaartefrance/"

  - title: "Facebook Mestre Parafuso"
    icon: "fa-facebook-f"
    url: "https://www.facebook.com/Cours.Capoeira.Nantes.Mestre.Parafuso"
    
  - title: "Youtube ACCB"
    icon: "fa-youtube"
    url: "https://www.youtube.com/@MusicaBrasileiraCapoeira"

  - title: "Youtube Mestre Parafuso"
    icon: "fa-youtube"
    url: "https://www.youtube.com/user/CapoeiraNantesACCB"

  - title: "Instagram Mestre Parafuso"
    icon: "fa-instagram"
    url: "https://www.instagram.com/capoeira_mestreparafuso/"
