baseURL = 'https://blog.ioguix.net/ja-accb-hugo/'
languageCode = 'fr-fr'
title = 'Capoeira Nantes Jacobina Arte'
theme = 'arcana'

SectionPagesMenu = "main"
# omit_header_text = "true"
# Paginate = 10

[params]
  attribution = false

  [[params.social]]
      title = "Facebook Jacobina Arte France"
      icon = "fa-facebook-f"
      url = "https://www.facebook.com/groups/jacobinaartefrance/"
  [[params.social]]
      title = "Facebook Mestre Parafuso"
      icon = "fa-facebook-f"
      url = "https://www.facebook.com/Cours.Capoeira.Nantes.Mestre.Parafuso"
  [[params.social]]
      title = "Youtube ACCB"
      icon = "fa-youtube"
      url = "https://www.youtube.com/@MusicaBrasileiraCapoeira"
  [[params.social]]
      title = "Youtube Mestre Parafuso"
      icon = "fa-youtube"
      url = "https://www.youtube.com/user/CapoeiraNantesACCB"
  [[params.social]]
      title = "Instagram Mestre Parafuso"
      icon = "fa-instagram"
      url = "https://www.instagram.com/capoeira_mestreparafuso/"
